// 1xxx -> Auth Errors
// 2xxx ->
// 3xxx -> Upload Errors
// 5xxx -> Server Errors

export const ErrorCodes = {
  998: {
    name: "UNIQUE_CONSTRAINT_FAILED",
    message: "Unique constraint failed",
    userMessage: "Already Exists",
    httpStatus: 400,
    category: "CLIENT",
    severity: "MEDIUM",
    retryable: false,
  },
  999: {
    name: "INTERNAL_SERVER_ERROR",
    message: "Internal server error",
    userMessage: "Something went wrong. Please try again later.",
    httpStatus: 500,
    category: "SERVER",
    severity: "HIGH",
    retryable: false,
  },
  1000: {
    name: "INVALID_CREDENTIALS",
    message: "Invalid email or password provided",
    userMessage:
      "Invalid email or password. Please check your credentials and try again.",
    httpStatus: 401,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: true,
  },

  1001: {
    name: "EMAIL_ALREADY_EXISTS",
    message: "Email already exists",
    userMessage: "Email already exists. Please use a different email.",
    httpStatus: 409,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1002: {
    name: "ACCOUNT_NOT_FOUND",
    message: "User account does not exist",
    userMessage: "No account found with this email. Please sign up first.",
    httpStatus: 404,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1003: {
    name: "ACCOUNT_LOCKED",
    message: "User account is temporarily locked",
    userMessage:
      "Your account has been temporarily locked. Please contact support.",
    httpStatus: 423,
    category: "AUTH",
    severity: "HIGH",
    retryable: false,
  },
  1004: {
    name: "TOKEN_EXPIRED",
    message: "Authentication token has expired",
    userMessage: "Your session has expired. Please log in again.",
    httpStatus: 401,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1005: {
    name: "INSUFFICIENT_PERMISSIONS",
    message: "User lacks required permissions",
    userMessage: "You don't have permission to perform this action.",
    httpStatus: 403,
    category: "AUTH",
    severity: "HIGH",
    retryable: false,
  },
  1006: {
    name: "PASSWORD_INCORRECT",
    message: "Password is incorrect",
    userMessage: "The password you entered is incorrect. Please try again.",
    httpStatus: 401,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1007: {
    name: "VALIDATION_ERROR",
    message: "Invalid input",
    userMessage: "Please provide either an email or phone number.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1008: {
    name: "USER_NOT_FOUND",
    message: "User not found",
    userMessage: "The requested user not found.",
    httpStatus: 404,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1009: {
    name: "USER_DONT_HAVE_PERMISSION",
    message: "User don't have permission",
    userMessage: "You don't have permission to perform this action.",
    httpStatus: 403,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1010: {
    name: "INVALID_TOKEN",
    message: "Invalid token",
    userMessage: "Invalid token. Please provide a valid token.",
    httpStatus: 401,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1011: {
    name: "ADDRESS_NOT_FOUND",
    message: "Address not found",
    userMessage: "Address not found. Please provide a valid address.",
    httpStatus: 404,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1012: {
    name: "PRODUCT_NOT_FOUND",
    message: "Product not found",
    userMessage: "Product not found. Please provide a valid product.",
    httpStatus: 404,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1013: {
    name: "PINCODE_NOT_SERVICEABLE",
    message: "Pin code is not serviceable",
    userMessage: "Pin code is not serviceable. Please try again.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1100: {
    name: "INVALID_DATE_FORMAT",
    message: "Invalid date format",
    userMessage: "The date format is invalid. Please use DDMMYYYY format.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1101: {
    name: "ACCOUNT_DORMANT",
    message: "Account is dormant",
    userMessage: "The account is dormant. Please contact support.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1102: {
    name: "ACCOUNT_ASSOCIATED_WITH_OTHER_AUTH",
    message: "Account is associated with other auth service",
    userMessage:
      "The account is associated with other auth service. Try Different auth service.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1103: {
    name: "OLD_PASSWORD_INCORRECT",
    message: "Old password is incorrect",
    userMessage: "The old password you entered is incorrect. Please try again.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1104: {
    name: "NEW_PASSWORD_SAME_AS_OLD",
    message: "New password is same as old password",
    userMessage: "The new password cannot be the same as the old password.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1105: {
    name: "NEW_PASSWORD_TOO_SHORT",
    message: "New password is too short",
    userMessage: "The new password must be at least 6 characters long.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1106: {
    name: "OLD_PASSWORD_INVALID",
    message: "Old password is invalid",
    userMessage: "The old password you entered is invalid. Please try again.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1107: {
    name: "INVALID_RESET_SESSION",
    message: "Invalid reset session",
    userMessage: "Session invalid. Please try again.",
    httpStatus: 400,
    category: "AUTH",
    severity: "MEDIUM",
    retryable: false,
  },
  1200: {
    name: "FAQ_NOT_FOUND",
    message: "Faq not found",
    userMessage: "Faq not found. Please provide a valid faq.",
    httpStatus: 404,
    category: "FAQ",
    severity: "MEDIUM",
    retryable: false,
  },
  2000: {
    name: "PRODUCT_NOT_FOUND",
    message: "Product not found",
    userMessage: "Product unavailable. Please select a valid product.",
    httpStatus: 404,
    category: "PRODUCT",
    severity: "MEDIUM",
    retryable: false,
  },

  2001: {
    name: "PRODUCT_CREATION_FAILED",
    message: "Product creation failed",
    userMessage: "Product creation failed. Please try again.",
    httpStatus: 400,
    category: "PRODUCT",
    severity: "MEDIUM",
    retryable: false,
  },
  2002: {
    name: "CATEGORY_NOT_FOUND",
    message: "Category not found",
    userMessage: "Category not found. Please provide a valid category.",
    httpStatus: 404,
    category: "CATEGORY",
    severity: "MEDIUM",
    retryable: false,
  },
  2003: {
    name: "SUB_CATEGORY_NOT_FOUND",
    message: "SubCategory not found",
    userMessage: "SubCategory not found. Please provide a valid subCategory.",
    httpStatus: 404,
    category: "CATEGORY",
    severity: "MEDIUM",
    retryable: false,
  },
  2004: {
    name: "VARIANT_NOT_FOUND",
    message: "Variant not found",
    userMessage: "Variant not found. Please provide a valid variant.",
    httpStatus: 404,
    category: "VARIANT",
    severity: "MEDIUM",
    retryable: false,
  },
  2005: {
    name: "IMAGE_NOT_FOUND",
    message: "Image not found",
    userMessage: "Image not found. Please provide a valid image.",
    httpStatus: 404,
    category: "IMAGE",
    severity: "MEDIUM",
    retryable: false,
  },
  2006: {
    name: "ADDRESS_NOT_ASSOCIATED_WITH_USER",
    message: "Address not associated with user",
    userMessage:
      "Address not associated your account. Please provide a valid address.",
    httpStatus: 400,
    category: "ADDRESS",
    severity: "MEDIUM",
    retryable: false,
  },
  2007: {
    name: "ORDER_NOT_FOUND",
    message: "Order not found",
    userMessage: "Order not found. Please provide a valid order.",
    httpStatus: 404,
    category: "ORDER",
    severity: "MEDIUM",
    retryable: false,
  },
  2008: {
    name: "CART_ITEM_NOT_FOUND",
    message: "Cart item not found",
    userMessage: "Cart item not found. Please provide a valid cart item.",
    httpStatus: 404,
    category: "CART",
    severity: "MEDIUM",
    retryable: false,
  },
  2009: {
    name: "COLLECTION_ITEM_NOT_FOUND",
    message: "Collection item not found",
    userMessage:
      "Collection item not found. Please provide a valid collection item.",
    httpStatus: 404,
    category: "COLLECTION",
    severity: "MEDIUM",
    retryable: false,
  },

  // 3xxx -> Upload Errors
  3001: {
    name: "UPLOAD_FAILED",
    message: "Upload failed",
    userMessage: "Upload failed. Please try again.",
    httpStatus: 400,
    category: "UPLOAD",
    severity: "MEDIUM",
    retryable: false,
  },
  3002: {
    name: "INVALID_FILE_FORMAT",
    message: "Invalid file format",
    userMessage: "Invalid file format. Please upload a valid file.",
    httpStatus: 400,
    category: "UPLOAD",
    severity: "MEDIUM",
    retryable: false,
  },
  3003: {
    name: "FILE_NAME_REQUIRED",
    message: "File name is required",
    userMessage: "File name is required. Please provide a valid file name.",
    httpStatus: 400,
    category: "UPLOAD",
    severity: "MEDIUM",
    retryable: false,
  },

  4000: {
    name: "RAZORPAY_WEBHOOK_INVALID",
    message: "Razorpay webhook invalid",
    userMessage: "Invalid Signature.",
    httpStatus: 400,
    category: "WEBHOOK",
    severity: "MEDIUM",
    retryable: false,
  },
};
